### ISSUE TITLE
Colored Line

### ISSUE THREAD

**Issue by ewolf90** [ewolf90/andromeda#4]
Colored line from header appears in the main content area. Error only appears in Firefox.

**Comment by ewolf90** [comment]
Unable to reproduce bug.

**Comment by spc0806** [comment]
Reinstalled skin after updates to fix security issues and line reappeared.

<img width="1043" alt="Screen Shot 2020-08-27 at 23 27 52" src="https://user-images.githubusercontent.com/25512133/91517923-00e9b280-e8bd-11ea-8712-7e94a333622d.png">
